### ISSUE TITLE
data2mem.exe doesn't support Spartan-6

### ISSUE THREAD

**Issue by kolontsov** [GadgetFactory/Papilio-Loader#11]
"data2mem.exe -h support" doesn't show Spartan-6 as supported chip, so Papilio Loader 2.6 can't load bmm/hex for bitfile which was generated for Papilio Pro. I've replaced it with latest data2mem.exe from Xilinx installation, everything works.

**Comment by jackgassett** [comment]
Thank you,

I think this is fixed in 2.8.
