### ISSUE TITLE
libftdi not found in configure in Gentoo x86_64

### ISSUE THREAD

**Issue by AlmuHS** [GadgetFactory/Papilio-Loader#18]
Hi all:

I'm trying to compile papilio-prog in a Gentoo x86_64 system

When I try to compile papilio-prog, in the configure step, i found this error:
 ```configure: error: Package requirements (libftdi >= 0.19) were not met:

No package 'libftdi' found`

I have installed libftdi in /usr/lib/libftdi1.so, and I set a link in /usr/lib32/libftdi.so.1, unsuccessfull

How can I solve this problem?

**Comment by AlmuHS** [comment]
I solved the problem, installing other older version of libftdi

**Comment by olofwalker** [comment]
A workaround for this (at least on my Fedora system) is to compile from source and after running `./autogen.sh` edit the `configure` file, replacing 'libftdi' with 'libftdi1` everywhere (make sure to check with `pkg-config --cflags libftdi1` that you actually have this package installed).

After that you just `./configure && make`

There is probably a better way todo this, but I just needed the binary working.

**Comment by AlmuHS** [comment]
I did this, but now I have other error in compile phase

[make_papilio.txt](https://github.com/GadgetFactory/Papilio-Loader/files/1714378/make_papilio.txt)

**Comment by AlmuHS** [comment]
Solved: Removed directory, reclone repository and change libftdi to libftdi1 in configure file
